require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Layout/LineLength:
  Max: 160

Rails/BulkChangeTable:
  Enabled: false

Metrics/MethodLength:
  Max: 120

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 30
